version: '2'
services:
 hub:
   image: selenium/hub
   container_name: hub
   ports:
     - "4444:4444"
     
 samsung_galaxy:
   image: budtmo/docker-android-x86-11.0
   privileged: true
   depends_on:
     - hub
   ports:
     - "6280:6280/tcp"
     - "5555:5555/tcp"
   volumes:
     - ./swiggy-3-69-1.apk:/root/tmp
#     - ./video-nexus_7.1.1:/tmp/video
   environment:
     - DEVICE=Samsung Galaxy S6
     - CONNECT_TO_GRID=True
     - APPIUM=true
     - SELENIUM_HOST=hub
     - MOBILE_WEB_TEST=true
#     - AUTO_RECORD=True

 