version: '3'

services:
  selenium-hub:
    image: selenium/hub:3.8.1
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    expose:
      - "4444"
    environment:
      GRID_MAX_SESSION: 5
      GRID_BROWSER_TIMEOUT: 100000
      GRID_TIMEOUT: 90000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 300000
  
  android-emulator:
    image: budtmo/docker-android-x86-10.0
#    build:
#      context: .
#      dockerfile: ./docker/headless-docker-android/Dockerfile
#    ports:
#      - 6080:6080
#     - 4723:4723
#    - 5555:5555
    privileged: true
    expose:
      - "6080"
      - "4723"
      - "5037" 
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=True
      - APPIUM=true
      - APPIUM_HOST=android-emulator
      - APPIUM_PORT=4723
      - SELENIUM_HOST=selenium-hub
      - SELENIUM_PORT=4444
      - MOBILE_WEB_TEST=True